export const books = {
    books: [
        {
            id: 1,
            title: "To Kill a Mockingbird",
            author: "Harper Lee",
            genre: "Fiction",
            totalCopies: 25,
            availableCopies: 18,
        },
        {
            id: 2,
            title: "1984",
            author: "George Orwell",
            genre: "Fiction",
            totalCopies: 15,
            availableCopies: 8,
        },
        {
            id: 3,
            title: "The Alchemist",
            author: "Paulo Coelho",
            genre: "Fiction",
            totalCopies: 30,
            availableCopies: 22,
        },
        {
            id: 4,
            title: "The Lean Startup",
            author: "Eric Ries",
            genre: "Business",
            totalCopies: 20,
            availableCopies: 12,
        },
        {
            id: 5,
            title: "Harry Potter and the Sorcerer's Stone",
            author: "J.K. Rowling",
            genre: "Fantasy",
            totalCopies: 40,
            availableCopies: 28,
        },
        {
            id: 6,
            title: "The Great Gatsby",
            author: "F. Scott Fitzgerald",
            genre: "Fiction",
            totalCopies: 18,
            availableCopies: 10,
        },
        {
            id: 7,
            title: "Pride and Prejudice",
            author: "Jane Austen",
            genre: "Fiction",
            totalCopies: 25,
            availableCopies: 15,
        },
        {
            id: 8,
            title: "The Hunger Games",
            author: "Suzanne Collins",
            genre: "Science Fiction",
            totalCopies: 35,
            availableCopies: 22,
        },
        {
            id: 9,
            title: "The Da Vinci Code",
            author: "Dan Brown",
            genre: "Mystery",
            totalCopies: 28,
            availableCopies: 16,
        },
        {
            id: 10,
            title: "The Kite Runner",
            author: "Khaled Hosseini",
            genre: "Fiction",
            totalCopies: 22,
            availableCopies: 14,
        },
        {
            id: 11,
            title: "The Book Thief",
            author: "Markus Zusak",
            genre: "Historical Fiction",
            totalCopies: 30,
            availableCopies: 20,
        },
        {
            id: 12,
            title: "The Catcher in the Rye",
            author: "J.D. Salinger",
            genre: "Fiction",
            totalCopies: 18,
            availableCopies: 12,
        },
        {
            id: 13,
            title: "The Hobbit",
            author: "J.R.R. Tolkien",
            genre: "Fantasy",
            totalCopies: 25,
            availableCopies: 18,
        },
        {
            id: 14,
            title: "The Lord of the Rings",
            author: "J.R.R. Tolkien",
            genre: "Fantasy",
            totalCopies: 35,
            availableCopies: 22,
        },
        {
            id: 15,
            title: "The Chronicles of Narnia",
            author: "C.S. Lewis",
            genre: "Fantasy",
            totalCopies: 28,
            availableCopies: 20,
        },
        {
            id: 16,
            title: "The Fault in Our Stars",
            author: "John Green",
            genre: "Young Adult",
            totalCopies: 22,
            availableCopies: 16,
        },
        {
            id: 17,
            title: "The Girl on the Train",
            author: "Paula Hawkins",
            genre: "Mystery",
            totalCopies: 30,
            availableCopies: 18,
        },
        {
            id: 18,
            title: "Gone Girl",
            author: "Gillian Flynn",
            genre: "Mystery",
            totalCopies: 25,
            availableCopies: 15,
        },
        {
            id: 19,
            title: "The Martian",
            author: "Andy Weir",
            genre: "Science Fiction",
            totalCopies: 20,
            availableCopies: 12,
        },
        {
            id: 20,
            title: "The Hitchhiker's Guide to the Galaxy",
            author: "Douglas Adams",
            genre: "Science Fiction",
            totalCopies: 18,
            availableCopies: 10,
        },
        {
            id: 21,
            title: "The Giver",
            author: "Lois Lowry",
            genre: "Young Adult",
            totalCopies: 25,
            availableCopies: 18,
        },
        {
            id: 22,
            title: "The Maze Runner",
            author: "James Dashner",
            genre: "Young Adult",
            totalCopies: 30,
            availableCopies: 22,
        },
        {
            id: 23,
            title: "The Divergent Series",
            author: "Veronica Roth",
            genre: "Young Adult",
            totalCopies: 28,
            availableCopies: 16,
        },
        {
            id: 24,
            title: "The Hunger Games Trilogy",
            author: "Suzanne Collins",
            genre: "Science Fiction",
            totalCopies: 35,
            availableCopies: 24,
        },
        {
            id: 25,
            title: "The Handmaid's Tale",
            author: "Margaret Atwood",
            genre: "Fiction",
            totalCopies: 22,
            availableCopies: 14,
        },
        {
            id: 26,
            title: "The Shining",
            author: "Stephen King",
            genre: "Horror",
            totalCopies: 18,
            availableCopies: 10,
        },
        {
            id: 27,
            title: "The Stand",
            author: "Stephen King",
            genre: "Horror",
            totalCopies: 25,
            availableCopies: 18,
        },
        {
            id: 28,
            title: "The Green Mile",
            author: "Stephen King",
            genre: "Fiction",
            totalCopies: 30,
            availableCopies: 22,
        },
        {
            id: 29,
            title: "The Outsiders",
            author: "S.E. Hinton",
            genre: "Young Adult",
            totalCopies: 28,
            availableCopies: 20,
        },
        {
            id: 30,
            title: "The Perks of Being a Wallflower",
            author: "Stephen Chbosky",
            genre: "Young Adult",
            totalCopies: 22,
            availableCopies: 16,
        },
    ],
};

export const tableHeadings = [
    "Title",
    "Author",
    "Genre",
    "Total Copies",
    "Available Copies",
];
